name: On Pull Request
on:
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore
    - name: Pack Nuget Package
      env:
        RELEASE_VERSION: 0.0.0
      run: dotnet pack
              --configuration Release
               -p:NuspecFile=pack.nuspec
               -p:NuspecProperties="version=$RELEASE_VERSION"
